INSTALL_TARGET_PROCESSES = SpringBoard

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = NotToday13


DEBUG = 0

NotToday13_FILES = Tweak.x
NotToday13_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
